import { Engineer, Project, Proposal } from '@/types'

export const mockEngineers: Engineer[] = [
  {
    id: 'demo-e1',
    name: '田中 健太',
    age: 28,
    gender: '男性',
    source_company: 'テクノソリューションズ株式会社',
    affiliation: '2社先正社員',
    skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Docker', 'Git'],
    processes: ['要件定義', '基本設計', '詳細設計', '実装', 'テスト'],
    certifications: ['基本情報技術者', '応用情報技術者'],
    work_style: 'hybrid',
    sales_status: '営業中',
    available_date: '2026-04-01',
    prefecture: '東京都',
    nearest_station: 'JR渋谷駅',
    rate_min: 600000,
    rate_max: 750000,
    desired_rate: null,
    experience_years: 5,
    notes: 'Javaを中心としたバックエンド開発が得意。チームリーダー経験あり。コミュニケーション能力が高く、顧客折衝も可能。',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-01-15T00:00:00Z',
    created_by: null,
    created_by_name: '営業 山田',
  },
  {
    id: 'demo-e2',
    name: '鈴木 美咲',
    age: 25,
    gender: '女性',
    source_company: 'デジタルクリエイト株式会社',
    affiliation: '1社先正社員',
    skills: ['Python', 'Django', 'AWS', 'pandas', 'SQL'],
    processes: ['詳細設計', '実装', 'テスト'],
    certifications: ['AWS Solutions Architect Associate'],
    work_style: 'remote',
    sales_status: '営業中',
    available_date: '2026-04-15',
    prefecture: '神奈川県',
    nearest_station: '横浜駅',
    rate_min: 550000,
    rate_max: 650000,
    desired_rate: null,
    experience_years: 3,
    notes: 'データエンジニアリング・機械学習パイプライン構築の経験あり。フルリモート希望。',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-02-01T00:00:00Z',
    created_by: null,
    created_by_name: '営業 山田',
  },
  {
    id: 'demo-e3',
    name: '山本 拓也',
    age: 31,
    gender: '男性',
    source_company: 'フロンティアシステム株式会社',
    affiliation: '2社先正社員',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'GraphQL'],
    processes: ['基本設計', '詳細設計', '実装', 'テスト'],
    certifications: [],
    work_style: 'hybrid',
    sales_status: '並行営業中',
    available_date: '2026-05-01',
    prefecture: '大阪府',
    nearest_station: '梅田駅',
    rate_min: 650000,
    rate_max: 800000,
    desired_rate: null,
    experience_years: 6,
    notes: 'フロントエンド専門。UX改善・パフォーマンス最適化の実績多数。デザイナーとの協業経験豊富。',
    created_at: '2026-02-10T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
    created_by: null,
    created_by_name: '営業 佐々木',
  },
  {
    id: 'demo-e4',
    name: '佐藤 雄一',
    age: 35,
    gender: '男性',
    source_company: 'インフラプロ株式会社',
    affiliation: '1社先正社員',
    skills: ['AWS', 'Terraform', 'Kubernetes', 'Docker', 'Linux', 'Python'],
    processes: ['要件定義', '基本設計', '実装', '運用・保守'],
    certifications: ['AWS Solutions Architect Professional', 'LPIC-2'],
    work_style: 'remote',
    sales_status: '稼働中',
    available_date: '2026-06-01',
    prefecture: '東京都',
    nearest_station: '新宿駅',
    rate_min: 800000,
    rate_max: 1000000,
    desired_rate: null,
    experience_years: 10,
    notes: 'インフラ・クラウド構築のスペシャリスト。現在別案件稼働中（6月終了予定）。大規模システムのマイグレーション実績あり。',
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
    created_by: null,
    created_by_name: '営業 佐々木',
  },
  {
    id: 'demo-e5',
    name: '高橋 彩',
    age: 23,
    gender: '女性',
    source_company: 'ウェブクラフト株式会社',
    affiliation: '1社先正社員',
    skills: ['PHP', 'Laravel', 'MySQL', 'Vue.js', 'HTML/CSS'],
    processes: ['詳細設計', '実装', 'テスト'],
    certifications: ['基本情報技術者'],
    work_style: 'onsite',
    sales_status: '営業中',
    available_date: '2026-04-01',
    prefecture: '愛知県',
    nearest_station: '名古屋駅',
    rate_min: 450000,
    rate_max: 550000,
    desired_rate: null,
    experience_years: 2,
    notes: 'PHP/LaravelでのWeb開発経験。キャッチアップが早く、成長意欲が高い。',
    created_at: '2026-03-10T00:00:00Z',
    updated_at: '2026-03-10T00:00:00Z',
    created_by: null,
    created_by_name: '営業 山田',
  },
]

export const mockProjects: Project[] = [
  {
    id: 'demo-p1',
    project_name: '金融系基幹システム刷新',
    client_name: '大手都市銀行',
    provider_company: 'システム開発会社A',
    required_skills: ['Java', 'Spring Boot', 'Oracle', 'Docker'],
    status: '営業中',
    work_style: 'hybrid',
    start_date: '2026-05-01',
    end_date: null,
    prefecture: '東京都',
    nearest_station: '大手町駅',
    budget_min: 700000,
    budget_max: 900000,
    headcount: 2,
    contract_type: '準委任',
    work_hours: '140〜180h',
    interview_count: '2回',
    age_limit: '〜40歳',
    nationality: null,
    freelancer: '不可',
    supply_chain: '2社',
    description: 'COBOLで構築されたレガシーシステムをJava/Spring Bootへ移行するプロジェクト。設計フェーズから参画可能。チームは10名規模で、アーキテクト1名・開発者2名を募集。',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-02-01T00:00:00Z',
    created_by: null,
    created_by_name: '営業 山田',
  },
  {
    id: 'demo-p2',
    project_name: 'ECサイト フロントエンド開発',
    client_name: 'アパレル大手',
    provider_company: null,
    required_skills: ['React', 'TypeScript', 'Next.js'],
    status: '営業中',
    work_style: 'remote',
    start_date: '2026-04-15',
    end_date: null,
    prefecture: '東京都',
    nearest_station: '六本木駅',
    budget_min: 650000,
    budget_max: 800000,
    headcount: 1,
    contract_type: '準委任',
    work_hours: '140〜160h',
    interview_count: '1回',
    age_limit: null,
    nationality: null,
    freelancer: '可',
    supply_chain: '1社',
    description: 'Next.js App Routerを使用したECサイトのフロントエンド刷新。デザインシステムの構築も含む。フルリモート可。',
    created_at: '2026-02-15T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    created_by: null,
    created_by_name: '営業 佐々木',
  },
  {
    id: 'demo-p3',
    project_name: 'データ分析基盤 構築・運用',
    client_name: '製造業大手',
    provider_company: 'データソリューションズ株式会社',
    required_skills: ['Python', 'AWS', 'SQL', 'Airflow'],
    status: '面談調整中',
    work_style: 'hybrid',
    start_date: '2026-06-01',
    end_date: null,
    prefecture: '愛知県',
    nearest_station: '名古屋駅',
    budget_min: 700000,
    budget_max: 850000,
    headcount: 1,
    contract_type: '準委任',
    work_hours: '160〜180h',
    interview_count: '2回',
    age_limit: '〜45歳',
    nationality: null,
    freelancer: null,
    supply_chain: '2社',
    description: 'AWS上でのデータパイプライン構築・Airflowによるワークフロー管理。機械学習モデルのデプロイ経験があれば尚可。',
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
    created_by: null,
    created_by_name: '営業 山田',
  },
  {
    id: 'demo-p4',
    project_name: '社内業務管理システム開発',
    client_name: '中堅物流会社',
    provider_company: null,
    required_skills: ['PHP', 'Laravel', 'MySQL', 'Vue.js'],
    status: '成約',
    work_style: 'onsite',
    start_date: '2026-04-01',
    end_date: '2026-09-30',
    prefecture: '大阪府',
    nearest_station: '本町駅',
    budget_min: 500000,
    budget_max: 600000,
    headcount: 1,
    contract_type: '準委任',
    work_hours: '140〜180h',
    interview_count: '1回',
    age_limit: null,
    nationality: null,
    freelancer: null,
    supply_chain: '1社',
    description: '在庫管理・配送管理システムをLaravel/Vue.jsで新規開発。要件定義から参画。',
    created_at: '2026-03-10T00:00:00Z',
    updated_at: '2026-03-10T00:00:00Z',
    created_by: null,
    created_by_name: '営業 佐々木',
  },
]

export const mockProposals: Proposal[] = [
  {
    id: 'demo-pr1',
    engineer_id: 'demo-e1',
    project_id: 'demo-p1',
    proposed_date: '2026-02-20',
    affiliation: 'テクノソリューションズ株式会社',
    client_name: '大手都市銀行',
    status: '面談済',
    created_at: '2026-02-20T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
    engineers: { name: '田中 健太', affiliation: 'テクノソリューションズ株式会社' },
    projects: { project_name: '金融系基幹システム刷新', client_name: '大手都市銀行' },
  },
  {
    id: 'demo-pr2',
    engineer_id: 'demo-e2',
    project_id: 'demo-p3',
    proposed_date: '2026-03-05',
    affiliation: 'デジタルクリエイト株式会社',
    client_name: '製造業大手',
    status: '面談調整中',
    created_at: '2026-03-05T00:00:00Z',
    updated_at: '2026-03-05T00:00:00Z',
    engineers: { name: '鈴木 美咲', affiliation: 'デジタルクリエイト株式会社' },
    projects: { project_name: 'データ分析基盤 構築・運用', client_name: '製造業大手' },
  },
  {
    id: 'demo-pr3',
    engineer_id: 'demo-e3',
    project_id: 'demo-p2',
    proposed_date: '2026-02-28',
    affiliation: 'フロンティアシステム株式会社',
    client_name: 'アパレル大手',
    status: '成約',
    created_at: '2026-02-28T00:00:00Z',
    updated_at: '2026-03-15T00:00:00Z',
    engineers: { name: '山本 拓也', affiliation: 'フロンティアシステム株式会社' },
    projects: { project_name: 'ECサイト フロントエンド開発', client_name: 'アパレル大手' },
  },
  {
    id: 'demo-pr4',
    engineer_id: 'demo-e5',
    project_id: 'demo-p4',
    proposed_date: '2026-03-12',
    affiliation: 'ウェブクラフト株式会社',
    client_name: '中堅物流会社',
    status: '提案中',
    created_at: '2026-03-12T00:00:00Z',
    updated_at: '2026-03-12T00:00:00Z',
    engineers: { name: '高橋 彩', affiliation: 'ウェブクラフト株式会社' },
    projects: { project_name: '社内業務管理システム開発', client_name: '中堅物流会社' },
  },
  {
    id: 'demo-pr5',
    engineer_id: 'demo-e1',
    project_id: 'demo-p2',
    proposed_date: '2026-03-01',
    affiliation: 'テクノソリューションズ株式会社',
    client_name: 'アパレル大手',
    status: '見送り',
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-10T00:00:00Z',
    engineers: { name: '田中 健太', affiliation: 'テクノソリューションズ株式会社' },
    projects: { project_name: 'ECサイト フロントエンド開発', client_name: 'アパレル大手' },
  },
]
